from snakemake.utils import min_version

#------------- min snakemake version ------------
min_version('6.7.0')

#------------- setup ------------
configfile: 'config/config.yaml'

report: 'report/workflow.rst'

#------------- load rules ------------

include: 'rules/common.smk'
if process_from_bcl:
    include: 'rules/demultiplex.smk'
include: 'rules/qc.smk'
include: 'rules/sc.smk'
include: 'rules/align.smk'

#------------- workflow ------------

if process_from_bcl:
    rule all:
        input:
            get_bcl2fastq_output(),
            get_mergelanes_output(),
            get_fastqc_output(),
            get_fastqscreen_output(),
            'results/qc_metrics/multiqc_report.html',
            get_trim_barcode_output(),
            get_align_output()

else:
    rule all:
        input:
            get_fastqc_output(),
            get_fastqscreen_output(),
            'results/qc_metrics/multiqc_report.html',
            get_trim_barcode_output(),
            get_align_output()

