# if set to false, will process from fastq files
process_from_bcl: False

# config file for Fastq Screen
FastqScreen_config: config/fastq_screen.conf

# sample sheet for bcl2fastq conversion
sample_sheet: bcl_input/SampleSheet.csv

# directory with raw bcl data
bcl_input: bcl_input

# number of sequencing lanes
lanes: 4

ref:
    # gene GTF reference used by STAR
    gtf: /stornext/Projects/score/Indexes/STAR/genes.gtf
    # STAR index
    star_index: /stornext/Projects/score/Indexes/STAR/GRCh38p13_STAR_2-7-8a

filter_settings:
    # affects read filter settings passed to scpipe::sc_trim_barcode
    # rmlow param
    remove_lowqual_reads: TRUE
    # rmN param (remove reads with Ns in barcode or UMI)
    remove_N_reads: FALSE
    # minq param
    min_base_q: 20
    # numbq param
    max_bases_below_qual: 2

read_structure:
    # sets whether read 1 contains the barcode information
    # note that everything will be reverse from scpipe's
    # perspective (R1 = R2 and vice versa)
    barcode_in_r1: TRUE
    # affects read_structure arguments in scpipe::sc_trim_barcode
    # bs1 param
    barcode_start_1: -1
    # bl1 param
    barcode_len_1: 0
    # bs2 param
    barcode_start_2: 6
    # bl2 param
    barcode_len_2: 7
    # us param
    umi_start: 0
    # ul param
    umi_len: 6

params:
    # extra commandline parameters for STAR (optional)
    star: '--limitBAMsortRAM 60000000000'

    # extra commandline parameters for bcl2fastq (optional)
    bcl2fastq: >
        --mask-short-adapter-reads 5
         --minimum-trimmed-read-length 5
         --loading-theads 4
         --writing-threads 4
         --processing-theads 14
